on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install --quiet --upgrade pip setuptools
    - name: test
      run: |
          python ci.py
