name: Internal Test
on:
  pull_request:

jobs:
  test:
    env:
      ARCHVAL_OPTIONS: pppe=1 psmi=1 xed_top_secret=xed-topsecret
    runs-on:
      - self-hosted
      - xed-runners
    container:
      image: ger-is-registry.caas.intel.com/bit/xed:0.0.6
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout mbuild
      uses: actions/checkout@v2
      with:
        repository: intel-innersource/libraries.isa.xed.mbuild
        path: mbuild
        token: ${{ secrets.PAT }}
    - name: Checkout xedext
      uses: actions/checkout@v2
      with:
        repository: intel-restricted/libraries.isa.xed.xedext
        path: xedext
        token: ${{ secrets.PAT }}
    - name: Checkout xed-topsecret
      uses: actions/checkout@v2
      with:
        repository: intel-restricted/libraries.isa.xed.xed-topsecret
        path: xed-topsecret
        token: ${{ secrets.PAT }}
    - name: test
      run: |
          python3 .github/scripts/ci_internal.py
