name: External Sanity
on:
  pull_request:
    branches:
      - external
  workflow_dispatch:

jobs:
  init:
    runs-on:
      - self-hosted
      - xed-runners
    outputs:
      test_matrix: ${{ steps.load_matrix.outputs.matrix }}
    steps:
      - name: Checkout xed for reusable actions
        uses: actions/checkout@v3
      - name: Set test matrix
        id: load_matrix
        uses: ./.github/actions/load-matrix
        with:
          matrix_kind: nightly

  test:
    needs: init
    strategy:
          fail-fast: false
          matrix: ${{fromJson(needs.init.outputs.test_matrix)}}
    runs-on:
      - self-hosted
      - xed-runners
      - ${{ matrix.os }}
    steps:
    - name: Checkout xed
      uses: actions/checkout@v3
      with:
        path: xed
    - name: Checkout mbuild
      uses: actions/checkout@v3
      with:
        repository: intelxed/mbuild
        ref: main
        path: mbuild
        token: ${{ secrets.PAT }}
    - name: test
      run: |
          cd xed
          python3 .github/scripts/sanity_external.py --compiler=${{matrix.compiler}} --version=${{matrix.ver}}
