name: External Sanity
on:
  pull_request:
    branches:
      - external
  workflow_dispatch:

jobs:
  test:
    strategy:
          fail-fast: false
          matrix: 
            os: ["Linux"]
            include:
            - os: "Linux"
    runs-on:
      - self-hosted
      - xed-runners
      - ${{ matrix.os }}
    steps:
    - name: Checkout xed
      uses: actions/checkout@v2
    - name: Checkout mbuild
      uses: actions/checkout@v2
      with:
        repository: intelxed/mbuild
        ref: main
        path: mbuild
        token: ${{ secrets.PAT }}
    - name: test
      run: |
          python3 .github/scripts/sanity_external.py
